package com.fbn.mtoplugin.response

data class PickupResponse(
    var ResponseCode: String? = "",
    var ResponseMessage: String? = "",
    var TransactionAmount: String? = "",
    var TransactionBatchReference: String? = "",
    var TransactionContractReference: String? = "",
    var TransactionCurrency: String? = "",
    var TransactionDate: String? = "",
    var TransactionDestinationCountryCode: String? = "",
    var TransactionDestinationCountryCurrency: String? = "",
    var TransactionId: String? = "",
    var TransactionMtoCode: String? = "",
    var TransactionNarration: String? = "",
    var TransactionPurposeCode: String? = "",
    var TransactionReceiverAccountNumber: String? = "",
    var TransactionReceiverBankCode: String? = "",
    var TransactionReceiverCity: String? = "",
    var TransactionReceiverEmailAddress: String? = "",
    var TransactionReceiverFirstName: String? = "",
    var TransactionReceiverGender: String? = "",
    var TransactionReceiverLastName: String? = "",
    var TransactionReceiverNationality: String? = "",
    var TransactionReceiverPhoneNumber: String? = "",
    var TransactionReceiverStreet: String? = "",
    var TransactionReference: String? = "",
    var TransactionSenderBirthDate: String? = "",
    var TransactionSenderCityAddress: String? = "",
    var TransactionSenderEmailAddress: String? = "",
    var TransactionSenderFirstName: String? = "",
    var TransactionSenderGender: String? = "",
    var TransactionSenderIdExpiryDate: String? = "",
    var TransactionSenderIdIssueDate: String? = "",
    var TransactionSenderIdIssuer: String? = "",
    var TransactionSenderIdNumber: String? = "",
    var TransactionSenderIdType: String? = "",
    var TransactionSenderImage: String? = "",
    var TransactionSenderLastName: String? = "",
    var TransactionSenderNationality: String? = "",
    var TransactionSenderOccupationCode: String? = "",
    var TransactionSenderPhoneNumber: String? = "",
    var TransactionSenderRelationship: String? = "",
    var TransactionSenderStreetAddress: String? = "",
    var TransactionSourceCode: String? = "",
    var TransactionSourceCountryCode: String? = "",
    var TransactionSourceCountryCurrency: String? = "",
    var TransactionStatus: String? = "",
    var TransactionTime: String? = "",
    var DestinationTransactionTime : String? = "",
    var TransactionInternalId : String? = "",
    var TransactionReceiverBirthDate : String? = "",
    var TransactionReceiverAddress : String? = ""
)



