package com.fbn.mtoplugin.request

data class PayTransRequest(
    var contractType: String?,
    var transactionAmount: String?,
    var transactionBatchReference: String?,
    var transactionChecker: String?,
    var transactionContractReference: String?,
    var transactionCreatedAt: String?,
    var transactionCurrency: String?,
    var transactionDate: String?,
    var transactionDebitAccount: String?,
    var transactionDestinationCountryCode: String?,
    var transactionDestinationCountryCurrency: String?,
    var transactionId: String?,
    var transactionMaker: String?,
    var transactionMtoCode: String?,
    var transactionNarration: String?,
    var transactionPayoutLocationCode: String?,
    var transactionPurposeCode: String?,
    var transactionReceiverAccountNumber: String?,
    var transactionReceiverId: String?,
    var transactionReceiverBankCode: String?,
    var transactionReceiverCity: String?,
    var transactionReceiverEmailAddress: String?,
    var transactionReceiverFirstName: String?,
    var transactionReceiverGender: String?,
    var transactionReceiverLastName: String?,
    var transactionReceiverNationality: String?,
    var transactionReceiverPhoneNumber: String?,
    var transactionReceiverStreet: String?,
    var transactionReceiverBirthDate: String?,
    var transactionReference: String?,
    var transactionPayoutRemark: String?,
    var transactionResponse: String?,
    var transactionResponseCode: String?,
    var transactionResponseMessage: String?,
    var transactionSenderBirthDate: String?,
    var transactionSenderCityAddress: String?,
    var transactionSenderEmailAddress: String?,
    var transactionSenderFirstName: String?,
    var transactionSenderGender: String?,
    var transactionSenderIdExpiryDate: String?,
    var transactionSenderIdIssueDate: String?,
    var transactionSenderIdIssuer: String?,
    var transactionSenderIdNumber: String?,
    var transactionSenderIdType: String?,
    var transactionSenderImage: String?,
    var transactionSenderLastName: String?,
    var transactionSenderNationality: String?,
    var transactionSenderOccupationCode: String?,
    var transactionSenderPhoneNumber: String?,
    var transactionSenderRelationship: String?,
    var transactionSenderStreetAddress: String?,
    var transactionSoleId: String?,
    var transactionSourceCode: String?,
    var transactionSourceCountryCode: String?,
    var transactionSourceCountryCurrency: String?,
    var transactionStatus: String?,
    var transactionTime: String?,
    var transactionUpdatedAt: String?,
    var responseCode: String? = null,
    var responseMessage: String? = null,
    var transactionInternalId: String? = null,
    var transactionReservationId: String? = null,
    var transactionExtraData: String?,
    var transactionReceiverIDDocumentNumber: String?,
    var transactionReceiverIDDocumentTypeCode: String?,
    var transactionReceiverIDDocumentExpirationDate: String?,
    var transactionReceiverIDDocumentDeliveryDate: String?
    )